### ISSUE TITLE
OpenInformix Ifxpy driver building on Solaris

### ISSUE THREAD

**Issue by Indrajith01** [OpenInformix/IfxPy#1]
Dear All ,
      We have successfully build the IfxPy driver on Redhat Linux platform and connected to the Informix db and done CRUD operations. But we were unable to find any IfxPy source files on Solaris platform .  There is an urgent customer requirement to use python with Informix on Solaris.We would like to know more details about IfxPy driver on Solaris platform . (Whether it is being developed, and releasing date of the driver etc)

Thanks & Kind Regards
Indrajith (Cybersoft-SRILANKA)

**Comment by Indrajith01** [comment]
Hi Satyan,

Python3.6  was built on Solaris 11 succefully with out errors. I have followed the same url and same steps(Source compiling steps under Linux ). But when IfxPy driver is being configured following errors are coming and stops and exiting the process.

gcc -shared -R/usr/local/lib build/temp.solaris-2.11-sun4v.32bit-3.6/ifxpyc.o -L/opt/ibm/csdk/lib/cli -L/work/dev/Python3/Lib -L. -lifdmr -lthcli -lpython3.6m -o build/lib.solaris-2.11-sun4v.32bit-3.6/IfxPy.so
ld: fatal: file /opt/ibm/csdk/lib/cli/libifdmr.so: wrong ELF class: ELFCLASS64
ld: fatal: file /opt/ibm/csdk/lib/cli/libthcli.so: wrong ELF class: ELFCLASS64
ld: fatal: library -lpython3.6m: not found
collect2: error: ld returned 1 exit status

OS: Solaris 11 SPARC 64 bit 
python version : python3.6.5 
gcc version 4.8.2 
PIP version 10
CSDK version : CSDK_4.10.FC9_SOL_SPARC_64 

  Please give your suggestions / workaround /support regarding this problem.

Thanks & Kind Regards
Indrajith

**Comment by Indrajith01** [comment]
Hi Satyan,

 If possible can you please send the steps to build IfxPy (Informix Python driver) driver on Solaris 10/11 servers. This is an urgent requirement from the customer .So we are expecting a quick resolution .

Thanks

**Comment by jsagrera** [comment]
Solaris build instructions in notes/SolarisBuild-note1.md
