### ISSUE TITLE
[Informix][Informix ODBC Driver]Invalid string or buffer length. SQLCODE=-11071

### ISSUE THREAD

**Issue by Marc176** [OpenInformix/IfxPy#10]
I opened a new issue for my college:

"I looked into IfxPy/tests/test_045_FetchTupleBinaryData_01.py and there it looks like you could simply do an exec_immediate without explicit bind_param calls. I tried that with a column of type "byte" but I only get an Error:

Exception: Column binding cannot be done: [Informix][Informix ODBC Driver]Invalid string or buffer length. SQLCODE=-11071"

**Comment by deokershesh** [comment]
Hi Marc176,

To understand the problem statement, are you saying that in test_000_PrepareDb.py file you are changing below statement and then running test_045_FetchTupleBinaryData_01.py without any change?

From:
-----
create = 'CREATE TABLE animal_pics (name VARCHAR(32), picture BLOB)'
To:
---
create = 'CREATE TABLE animal_pics (name VARCHAR(32), picture BYTE)'

**Comment by cypres-it** [comment]
No, I have this issue on a real world table where the column is of type BYTE.

Regarding the unit test: I do not have to change the files to get an error. If I run the tests unchanged it looks like this:

```
$ python -m unittest test_000_PrepareDb
..
----------------------------------------------------------------------
Ran 2 tests in 0.057s

OK
$ python -m unittest test_045_FetchTupleBinaryData_01
E.
======================================================================
ERROR: test_045_FetchTupleBinaryData_01 (test_045_FetchTupleBinaryData_01.IfxPyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_045_FetchTupleBinaryData_01.py", line 16, in test_045_FetchTupleBinaryData_01
    obj.assert_expect(self.run_test_045)
  File "testfunctions.py", line 82, in assert_expect
    self.assertEqual(self.capture(testFuncName), self.expected_IDS(callstack[1][1]))
  File "testfunctions.py", line 50, in capture
    func()
  File "test_045_FetchTupleBinaryData_01.py", line 22, in run_test_045
    row = IfxPy.fetch_tuple(result)
Exception: Column binding cannot be done:

----------------------------------------------------------------------
Ran 2 tests in 0.021s

FAILED (errors=1)
```

Any idea why the unit test is failing?

**Comment by Marc176** [comment]
@deokershesh could you please comment on this message from my college?

**Comment by deokershesh** [comment]
@Marc176, I am trying to reproduce the issue in my environment. Will update at the earliest.

**Comment by deokershesh** [comment]
@Marc176 ,

Looks like I had some issue with my old code. I downloaded the latest Python Informix driver code, recompiled and running the below sample code works perfectly. Could you try with the latest Python Informix driver code? Also try to switch to fetch_row() if fetch_tuple() reports any issue.

-------------
import os
import IfxPy

ConnStr = "SERVER=ol_informix1210;DATABASE=mydb;HOST=127.0.0.1;SERVICE=9088;"
conn = IfxPy.connect( ConnStr, "", "")


drop = 'DROP TABLE IF EXISTS animal_pics'
try:
  result = IfxPy.exec_immediate(conn, drop)
except:
  pass
create = 'CREATE TABLE animal_pics (name VARCHAR(32), picture BYTE)'
result = IfxPy.exec_immediate(conn, create)
animals = (\
  ('Spook', 'spook.png'),\
  ('Helmut', 'pic1.jpg'),\
)
insert = 'INSERT INTO animal_pics (name, picture) VALUES (?, ?)'
stmt = IfxPy.prepare(conn, insert)
if (not stmt):
  print ("Attempt to prepare statement failed.")
for animal in animals:
  name = animal[0]
  fileHandle = open(os.path.dirname(os.path.abspath(__file__)) + '/' + animal[1], 'rb')
  picture = fileHandle.read()
  if (not picture):
    print ("Could not retrieve picture '%s'." % animal[1])
  IfxPy.bind_param(stmt, 1, name, IfxPy.SQL_PARAM_INPUT)
  IfxPy.bind_param(stmt, 2, picture, IfxPy.SQL_PARAM_INPUT)
  result = IfxPy.execute(stmt)

## #######
## #######

fp = open("pic1_out.jpg", "wb")
result = IfxPy.exec_immediate(conn, "SELECT picture FROM animal_pics WHERE name = 'Helmut'")
#row = IfxPy.fetch_tuple(result)
row=IfxPy.fetch_row(result)
if row:
  fp.write(IfxPy.result(result, 0))
else:
  print (IfxPy.stmt_errormsg())
fp.close()
cmp = (open('pic1_out.jpg', 'rb').read() == open('pic1.jpg', 'rb').read())
print ('Are the files same? ', cmp)
---------------------

**Comment by cypres-it** [comment]
Thanks deokershesh, using fetch_row does indeed work. So the issue seems to be that fetch_tuple and fetch_assoc currently cannot handle binary data. Are there any plans to fix this?

**Comment by deokershesh** [comment]
@cypres-it, Thanks for confirmation that fetch_row works. Did you try with the latest version of Python Informix Driver? What's the CSDK version you are using? Which platform/OS you are using? In my case, I am using CSDK 4.10.FC12 on Windows 10.

**Comment by Marc176** [comment]
Hello,

we´re using Ubuntu 14.04 LTS 64bit with Informix 12.10 - details:

![image](https://user-images.githubusercontent.com/17454146/49018051-a886fd80-f18a-11e8-8c1f-d21c75cbcdac.png)

**Comment by deokershesh** [comment]
I need to setup Ubuntu environment. If you have not tried with latest Python code, please give a try.

**Comment by Marc176** [comment]
Hello,

any news regarding this issue @deokershesh  ?

**Comment by deokershesh** [comment]
@Marc176, I yet to get Ubuntu environment, currently occupied with release work. By the way, Did you get chance to try with latest Python Driver code? As its working (Both fetch_row & fetch_tuple ) for me on Windows and there is as such no platform specific code!

**Comment by cypres-it** [comment]
Okay I tested again with latest driver, but I am still getting an error:
```
$ python2.7 testBinary4.py
Traceback (most recent call last):
  File "testBinary4.py", line 34, in <module>
    row = IfxPy.fetch_tuple(result)
Exception: Column binding cannot be done:
```

This is the test script:
```
import os
import IfxPy
from config import config

conn = IfxPy.connect(*config)

drop = 'DROP TABLE IF EXISTS animal_pics'
try:
    result = IfxPy.exec_immediate(conn, drop)
except:
    pass
create = 'CREATE TABLE animal_pics (name VARCHAR(32), picture BYTE)'
result = IfxPy.exec_immediate(conn, create)
animals = (
    ('Spook', 'spook.png'),
    ('Helmut', 'pic1.jpg'),
)
insert = 'INSERT INTO animal_pics (name, picture) VALUES (?, ?)'
stmt = IfxPy.prepare(conn, insert)
if (not stmt):
    print ("Attempt to prepare statement failed.")
for animal in animals:
    name = animal[0]
    fileHandle = open(os.path.dirname(os.path.abspath(__file__)) + '/' + animal[1], 'rb')
    picture = fileHandle.read()
    if (not picture):
        print ("Could not retrieve picture '%s'." % animal[1])
    IfxPy.bind_param(stmt, 1, name, IfxPy.SQL_PARAM_INPUT)
    IfxPy.bind_param(stmt, 2, picture, IfxPy.SQL_PARAM_INPUT)
    result = IfxPy.execute(stmt)

fp = open("pic1_out.jpg", "wb")
result = IfxPy.exec_immediate(conn, "SELECT picture FROM animal_pics WHERE name = 'Helmut'")
row = IfxPy.fetch_tuple(result)
if row:
    fp.write(row[0])
else:
    print (IfxPy.stmt_errormsg())
    fp.close()
cmp = (open('pic1_out.jpg', 'rb').read() == open('pic1.jpg', 'rb').read())
print ('Are the files same? ', cmp)
```

And this is how I installed the driver:
```
cd /tmp
git clone https://github.com/OpenInformix/IfxPy.git
cd IfxPy/IfxPy
export CSDK_HOME=/opt/informix
export MY_PY_DIR=/usr
export LD_LIBRARY_PATH=${INFORMIXDIR}/lib:${INFORMIXDIR}/lib/esql:${INFORMIXDIR}/lib/cli
python2.7 -m pip install --user -I .
```

**Comment by Marc176** [comment]
And we dont use logging ! Maybe its important too

**Comment by Marc176** [comment]
@deokershesh any news here? We need this fixed..

**Comment by Marc176** [comment]
@deokershesh were you able to test it ?

**Comment by deokershesh** [comment]
@Marc176, Sorry didn't get enough time to work on this, currently busy with major release work. I am hoping the workaround suggested above which is working for you will make you to proceed for time being. I expect to come at the earliest possible on this issue.

**Comment by Marc176** [comment]
@deokershesh there is no workaround for us working. It does not work

**Comment by deokershesh** [comment]
May be I got it wrong, earlier comment says "Thanks deokershesh, using fetch_row does indeed work. So the issue seems to be that fetch_tuple and fetch_assoc currently cannot handle binary data. Are there any plans to fix this?"

Looks like fetch_row() doesn't solve your requirement.

**Comment by cypres-it** [comment]
While it is a workaround, we have a lot of dynamically generated SQL queries in our system where a workaround like this is hard to implement and we end up with a lot of hard to maintain special cases. So we really would like to be able to just use fetch_tuple/assoc anywhere without having to look at the types involved.

**Comment by deokershesh** [comment]
Yes, we will fix the issue. Unfortunately my RHEL environment is not sane! hence I configured Virtual Box with Ubuntu but that also having its own share of problems while installing certain tools/software. Thanks cypres-it for your patience. I am looking for sane machine which I could setup and debug on RHEL/Ubuntu as it doesn't reproduce on Windows.

**Comment by Marc176** [comment]
@deokershesh happy new year ;) Any news regarding this issue??

**Comment by Marc176** [comment]
@deokershesh everything ok? Did you find some time?

**Comment by jsagrera** [comment]
This commit should resolve the -11071 error when fetching BYTE data:

https://github.com/OpenInformix/IfxPy/commit/8bf93447e5d8b54f701fe99ffce1ecb48dc924d9

give it a try.

**Comment by jsagrera** [comment]
check last comment
