### ISSUE TITLE
Where can I download Ifxpy for ARM64 platform

### ISSUE THREAD

**Issue by rocky1001** [OpenInformix/IfxPy#13]
Hi,
I noticed the info below from readme: 
````
The driver has support for both Python 2.7 and Python 3x. It has been certified across all major development platforms such as ARM64 running Raspbian OS, Linux, and Windows; and no surprise, it works well on the Raspberry Pi3.
````
My problem is: Where can I download IfxPy for ARM64 platform?
Thanks.

**Comment by chestnutsj** [comment]
informix 官方应该只出了树莓派的arm 版本,树莓派只有32位的系统，你要64位干啥。。。

**Comment by rocky1001** [comment]
Thanks for replying.
I've compiled aarch64 version of Ifxpy by myself, thanks again.
