### ISSUE TITLE
execute_many does not work?

### ISSUE THREAD

**Issue by Marc176** [OpenInformix/IfxPy#2]
Any idea when it will be implemented?

    { "execute_many", (PyCFunction)IfxPy_execute_many, METH_VARARGS, "Execute SQL with multiple rows." }, // TODO

**Comment by deokershesh** [comment]
I will update you on the date of support, at the earliest possible.

**Comment by deokershesh** [comment]
Hi Marc176,

Did you try to use execute_many() OR was it more about "TODO" which is mentioned at the end of that statement? If, its about "TODO" then it appears its wrong and should be removed. The execute_many() is implemented and it works as follows. Please could you try and confirm?

===================
import IfxPy

ConStr="Driver={IBM INFORMIX ODBC DRIVER};SERVER=xyz;DATABASE=stores7;host=xyz;service=9088;protocol=onsoctcp"

conn=IfxPy.connect(ConStr,"user","password")
if conn:
     IfxPy.exec_immediate(conn, "DROP TABLE if exists t1")
     IfxPy.exec_immediate(conn, "CREATE TABLE t1 (c1 int, c2 char(10))")
     
     insert = "INSERT INTO t1 (c1,c2) VALUES (?,?)"
     params = ((1,'a'), (2,'b'), (3,'c'))
     stmt_insert = IfxPy.prepare(conn, insert)
     IfxPy.execute_many(stmt_insert, params)

     stmt = IfxPy.exec_immediate(conn, "SELECT * FROM t1")
     res = IfxPy.fetch_tuple(stmt)
     while res != False:
         print res[0],res[1]
         res = IfxPy.fetch_tuple(stmt)

$ python t2.py
1 a         
2 b         
3 c         
=================

**Comment by Marc176** [comment]
Yes, i was asking because i saw that //TODO remark.

I thought it only works in IfxPy DBi not in the native.

Your example just works fine - yes.
