### ISSUE TITLE
Don't deal Japanese.

### ISSUE THREAD

**Issue by arachan** [OpenInformix/IfxPy#23]
I tried IfxPy.

Install is work fine.

**But, don't coonect.**

It is error message under.

```
Exception: [Informix][Informix ODBC Driver][Informix]Error opening required code-set conversion object file. SQLCODE=-23104
```

I tried to connect Informix to use perl on same enviroment.

Perl is work fine.

Mybe.. IfxPy don't deal Japanese.

Don't Open code-set conversion object file.

Don't have Code-set conversion object?

No, Informix ClientSDK have code-set conversion object file.

```
$ cat /opt/IBM/Informix_ClientSDK/etc/gls/cm3/registry | grep -e utf8 -e sjis-s -e cp932                   
# codesetname	 number	 codeset hex
  sjis-s          932     # 0x03a4
  cp932           932     # 0x03a4 Japanese MS Windows Code Page 932
  utf8            57372   # 0xe01c  
```

- DB_LOCALE=sjis-s
- CLIENT_LOCALE=utf8

So, Code-set Conversion Object file is 03a4e01c.csv and e01c03a4.csv.

I search it.

Please watch under.

Informix Client SDK have Codeset Conversion Object file.

```
vagrant@debian10:/opt/IBM/Informix_Client-SDK/gls/cv9$ ls -l {e01c03a4.cvo,03a4e01c.cvo}
 -rw-r--r-- 1 root root  81121  2月 16  2019 03a4e01c.cvo
 -rw-r--r-- 1 root root 159162  2月 16  2019 e01c03a4.cvo

vagrant@debian10:/opt/IBM/Informix_Client-SDK/gls/lc11/ja_jp$ ls -l
 合計 116
 -rw-r--r-- 1 root root  7768  2月 16  2019 03a4.lco #sjis-s
 -rw-r--r-- 1 root root 10179  2月 16  2019 e006.lco
 -rw-r--r-- 1 root root 11411  2月 16  2019 e007.lco
 -rw-r--r-- 1 root root 85267  2月 16  2019 e01c.lco #utf8

```

## Environment

**Client**

- vagrant box [generic/debian10](https://app.vagrantup.com/generic/boxes/debian10[generic/debian10)
- Informix Client SDK 4.50FC1
- CLIENT_LOCALE=ja_jp.utf8

```
$ localectl
System Locale: LANG=ja_JP.UTF-8
               LANGUAGE=ja_JP:ja
    VC Keymap: n/a
    X11 Layout: us
    X11 Model: pc105
```

**Server**

- CentOS7
- Informix Dynamic Server 12.10FCWE12
- DB_LOCALE=ja_jp.sjis-s

## Procedure

```
# make csdk folder
$ mkdir csdk
# extract
$ tar -xvf clientsdk.4.10.FC9DE.LINUX.tar -C csdk
$ cd csdk
# Install Library for installclientcsdk 
$ sudo apt -y install libaio1 bc libncurses5 ncurses-bin libpam0g
$ sudo apt -y install libncurses5-dev libelf1 

# Install
$ sudo ./installclientcsdk -i console

# SET Environment Variables
# export INFORMIXDIR=/opt/IBM/informix # CSDK 4.10 
export INFORMIXDIR=/opt/IBM/Informix_Client-SDK #CSDK 4.50
export LD_LIBRARY_PATH=${INFORMIXDIR}/lib:${INFORMIXDIR}/lib/esql:${INFORMIXDIR}/lib/cli

# Make sqlhosts
$ sudo cp /opt/IBM/Informix_Client-SDK/etc/sqlhosts.std /opt/IBM/Informix_Client-SDK/etc/sqlhosts
$ vi /opt/IBM/Informix_Client-SDK/etc/sqlhosts
# ...etc....
servername        onsoctcp        serverip      21435
$

# SET DB_LOCALE
$ export DB_LOCALE=ja_jp.sjis-s

# SET CLIENT_LOCALE
$ export DB_LOCALE=ja_jp.utf8

# pip install
$ sudo apt install python3-pip

# Install IfxPy
$ pip3 install IfxPy --user

# make python file
$ vi ifxcnnt.py

# Execute Python3
$ python3 ifxcnnt.py
  Traceback (most recent call last):
   File "ifxcnnt.py", line 6, in <module>
     conn=IfxPy.connect(ConStr,"","")
 Exception: [Informix][Informix ODBC Driver][Informix]Error opening required code-set conversion object file. SQLCODE=-23104

```

**Comment by jsagrera** [comment]
Umm... I did a quick test on my linux box with 4.10.FC12 and have no problems connecting to a ja_jp.sjis database:

	informix@irk:/data/informix/IBM/OpenInformix/IfxPy/IfxPy/Examples# set | grep ja_jp
	CLIENT_LOCALE=ja_jp.utf8
	DB_LOCALE=ja_jp.utf8
	informix@irk:/data/informix/IBM/OpenInformix/IfxPy/IfxPy/Examples# cat ja.py 

	# Sample1.py
	import IfxPy

	def my_Sample():
		ConStr = "SERVER=irk1210;DATABASE=jajpsjis2;HOST=127.0.0.1;SERVICE=9088;PROTOCOL=onsoctcp;UID=informix;PWD=ximrofni;"

		try:
	.       # netstat -a | findstr  9088
			conn = IfxPy.connect( ConStr, "", "")
		except Exception as e:
			print ('ERROR: Connect failed')
			print ( e )
			quit()

		# Select records
		sql = "SELECT first 2 * FROM systables"
		stmt = IfxPy.exec_immediate(conn, sql)
		dictionary = IfxPy.fetch_both(stmt)

		rc = 0
		while dictionary != False:
			rc += 1
			print ("--  Record {0} --".format(rc))
			print ("c1 is : ",  dictionary[0])
			print ("c2 is : ", dictionary[1])
			print (" ")
			dictionary = IfxPy.fetch_both(stmt)

		print()
		print( "Total Record Selected {}".format(rc) )
		print ("Done")

	####### Run the sample function ######
	my_Sample()
	informix@irk:/data/informix/IBM/OpenInformix/IfxPy/IfxPy/Examples# python3 ja.py 
	--  Record 1 --
	c1 is :  systables
	c2 is :  informix                        
	 
	--  Record 2 --
	c1 is :  syscolumns
	c2 is :  informix                        
	 

	Total Record Selected 2
	Done
	informix@irk:/data/informix/IBM/OpenInformix/IfxPy/IfxPy/Examples# 


Before update CDSK, try collecting a GLS LOG file
set GLSLOG to "on" like:

	informix@irk:/data/informix/IBM/OpenInformix/IfxPy/IfxPy/Examples# export CLIENT_LOCALE=ja_bad.utf8
	informix@irk:/data/informix/IBM/OpenInformix/IfxPy/IfxPy/Examples# export GLSLOG=on
	informix@irk:/data/informix/IBM/OpenInformix/IfxPy/IfxPy/Examples# python3 ja.py 
	ERROR: Connect failed
	[Informix][Informix ODBC Driver][Informix]Unable to load locale categories. SQLCODE=-23101
	informix@irk:/data/informix/IBM/OpenInformix/IfxPy/IfxPy/Examples# grep bad gls.log
	Could not open: /data/informix/IBM/4.10.FC12/gls/lc11/os/ja_bad.utf8
	Could not open: /data/informix/IBM/4.10.FC12/gls/lc/os/ja_bad.utf8
	informix@irk:/data/informix/IBM/OpenInformix/IfxPy/IfxPy/Examples# 
	
Maybe there is something in the log that can tell us why it fails.

**Comment by jsagrera** [comment]
I can see the problem, need to review the code to see why it happens.

from dbaccess:

	root@irk:/data/informix/IBM/OpenInformix/IfxPy/IfxPy/Examples# grep Open gls.log
	Opened: /data/informix/IBM/4.10.FC12/gls/cm3/registry
	Opened: /data/informix/IBM/4.10.FC12/gls/lc11/ja_jp/e01c.lco
	Opened: /data/informix/IBM/4.10.FC12/gls/lc11/ja_jp/e01c.lco
	Opened: /data/informix/IBM/4.10.FC12/gls/lc11/ja_jp/e01c.lco
	Opened: /data/informix/IBM/4.10.FC12/gls/lc11/ja_jp/e01c.lco
	Opened: /data/informix/IBM/4.10.FC12/gls/lc11/ja_jp/e01c.lco
	Opened: /data/informix/IBM/4.10.FC12/gls/lc11/ja_jp/e01c.lco
	Opened: /data/informix/IBM/4.10.FC12/gls/cv9/e01c03a4.cvo
	Opened: /data/informix/IBM/4.10.FC12/gls/cv9/03a4e01c.cvo
	Opened: /data/informix/IBM/4.10.FC12/gls/lc11/ja_jp/03a4.lco
	Opened: /data/informix/IBM/4.10.FC12/gls/lc11/ja_jp/03a4.lco
	Opened: /data/informix/IBM/4.10.FC12/gls/lc11/ja_jp/03a4.lco
	Opened: /data/informix/IBM/4.10.FC12/gls/lc11/ja_jp/03a4.lco
	Opened: /data/informix/IBM/4.10.FC12/gls/lc11/ja_jp/03a4.lco
	Opened: /data/informix/IBM/4.10.FC12/gls/lc11/ja_jp/03a4.lco
	root@irk:/data/informix/IBM/OpenInformix/IfxPy/IfxPy/Examples# 

from python:

	root@irk:/data/informix/IBM/OpenInformix/IfxPy/IfxPy/Examples# python ja.py 
	ERROR: Connect failed
	[Informix][Informix ODBC Driver][Informix]Error opening required code-set conversion object file. SQLCODE=-23104
	root@irk:/data/informix/IBM/OpenInformix/IfxPy/IfxPy/Examples# grep -i open gls.log
	Opened: /data/informix/IBM/4.10.FC12/gls/cm3/registry
	Opened: /data/informix/IBM/4.10.FC12/gls/lc11/ja_jp/e01c.lco
	Opened: /data/informix/IBM/4.10.FC12/gls/lc11/ja_jp/e01c.lco
	Opened: /data/informix/IBM/4.10.FC12/gls/lc11/ja_jp/e01c.lco
	Opened: /data/informix/IBM/4.10.FC12/gls/lc11/ja_jp/e01c.lco
	Opened: /data/informix/IBM/4.10.FC12/gls/lc11/ja_jp/e01c.lco
	Opened: /data/informix/IBM/4.10.FC12/gls/lc11/ja_jp/e01c.lco
	Opened: /data/informix/IBM/4.10.FC12/gls/cv9/e01c03a4.cvo
	Opened: /data/informix/IBM/4.10.FC12/gls/cv9/03a4e01c.cvo
	Opened: /data/informix/IBM/4.10.FC12/gls/lc11/ja_jp/03a4.lco
	Opened: /data/informix/IBM/4.10.FC12/gls/lc11/ja_jp/03a4.lco
	Opened: /data/informix/IBM/4.10.FC12/gls/lc11/ja_jp/03a4.lco
	Opened: /data/informix/IBM/4.10.FC12/gls/lc11/ja_jp/03a4.lco
	Opened: /data/informix/IBM/4.10.FC12/gls/lc11/ja_jp/03a4.lco
	Opened: /data/informix/IBM/4.10.FC12/gls/lc11/ja_jp/03a4.lco
	Opened: /data/informix/IBM/4.10.FC12/gls/cm3/registry
	Opened: /data/informix/IBM/4.10.FC12/gls/lc11/en_us/0333.lco
	Opened: /data/informix/IBM/4.10.FC12/gls/lc11/en_us/0333.lco
	Opened: /data/informix/IBM/4.10.FC12/gls/lc11/en_us/0333.lco
	Opened: /data/informix/IBM/4.10.FC12/gls/lc11/en_us/0333.lco
	Opened: /data/informix/IBM/4.10.FC12/gls/lc11/en_us/0333.lco
	Opened: /data/informix/IBM/4.10.FC12/gls/lc11/en_us/0333.lco
	Could not open: /data/informix/IBM/4.10.FC12/gls/cv9/033303a4.cvo
	Could not open: /data/informix/IBM/4.10.FC12/gls/cv/033303a4.cvo
	root@irk:/data/informix/IBM/OpenInformix/IfxPy/IfxPy/Examples# 

it appears the driver tries to use 819 which of course fails as there is no conversion from any sjis to 8859-1.

**Comment by jsagrera** [comment]
Ok, it looks the environment variables are not properly passed, try specifying DB_LOCALE in the connection string, it should work:

 
	informix@irk:/data/informix/IBM/OpenInformix/IfxPy/IfxPy/Examples# grep ja_jp ja.py
		ConStr = "SERVER=irk1210;DATABASE=jajpsjiss;HOST=127.0.0.1;SERVICE=9088;PROTOCOL=onsoctcp;UID=informix;PWD=ximrofni;CLIENT_LOCALE=ja_jp.utf8;DB_LOCALE=ja_JP.sjis-s"
	informix@irk:/data/informix/IBM/OpenInformix/IfxPy/IfxPy/Examples# python3 ja.py
	--  Record 1 --
	c1 is :  systables
	c2 is :  informix                        
	 
	--  Record 2 --
	c1 is :  syscolumns
	c2 is :  informix                        
	 

	Total Record Selected 2
	Done
	informix@irk:/data/informix/IBM/OpenInformix/IfxPy/IfxPy/Examples#

**Comment by arachan** [comment]
Thank you, jsagrera.

Connected successes to write DB_LOCALE in connectionstring.
It code is work :-)
But, Another code don't work. :-<

```python
#! /usr/bin/env python3
import IfxPyDbi as dbapi2

ConnectionString="SERVER=servername;DATABASE=mrkdb;HOST=IP;SERVICE=21435;UID=username;PWD=password;PROTOCOL=onsoctcp;CLIENT_LOCALE=ja_jp.utf8;DB_LOCALE=ja_jp.sjis-s"
  
 conn=dbapi2.connect(ConnectionString,"","")
 cur=conn.cursor()
 cur.execute("select 得意先名 from 得意先m where 得意先cd=1")
 rows=cur.fetchall()
 
 for i,row in enumerate(rows):
 	print("Row",i,"value=",row)

cur.close()
conn.close()
 
 print("Done")
```

## IfxPy.fetch_row
Japanese Column Name don't work. :-(

code

```python
 # ommited ConnStr
 conn=IfxPy.connect(ConnStr,"","")
 sql="SELECT 得意先cd,得意先名 FROM 得意先m WHERE 得意先cd=1 or 得意先cd=2"
 stmt=IfxPy.exec_immediate(conn,sql)
 while IfxPy.fetch_row(stmt) != False:
     print (IfxPy.result(stmt, 1)) # work!
     print (IfxPy.result(stmt, "得意先名")) # Don't work
```

result
```bash 
 株式会社 東京支店
 Traceback (most recent call last):
 File "ifxcnnt.py", line 26, in <module>
 print (IfxPy.result(stmt, "得意先名")) 
 UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)  
```

## IfxPy.fetch_assoc and IfxPy.fetch_both
Segmentation fault :-(

code
```python
 # ommited ConnStr
 conn=IfxPy.connect(ConnStr,"","")
 sql="SELECT 得意先cd,得意先名 FROM 得意先m WHERE 得意先cd=1"
 stmt=IfxPy.exec_immediate(conn,sql)
 dic=IfxPy.fetch_assoc(stmt) # Segmentation fault
 while dic != False:
     print (dic[1])
     print (dic["得意先名"])
     dic=IfxPy.fetch_assoc(stmt)
```

```python	
# ommited ConnStr
 conn=IfxPy.connect(ConnStr,"","")
 sql="SELECT 得意先cd,得意先名 FROM 得意先m WHERE 得意先cd=1"
 stmt=IfxPy.exec_immediate(conn,sql)
 dic=IfxPy.fetch_both(stmt) # Segmentation fault
 while dic != False:
     print (dic[1])
     print (dic["得意先名"])
     dic=IfxPy.fetch_both(stmt)

```

result
```bash
 Segmentation fault
```

## IfxPy.fetch_tuple
work! :-)

code
```python
 # ommited ConnStr
 conn=IfxPy.connect(ConnStr,"","")
 sql="SELECT 得意先cd,得意先名 FROM 得意先m WHERE 得意先cd=1"
 stmt=IfxPy.exec_immediate(conn,sql)
 tuples=IfxPy.fetch_tuple(stmt)
 while tuples != False:
     print(tuples[1])
     tuples=IfxPy.fetch_tuple(stmt)
```

result
```bash
 株式会社
 株式会社 東京支店
```

**Comment by jsagrera** [comment]
Currently only ASCII identifiers can be used. The driver tries to convert things like columns names to ASCII and if it can't (like in you example) it will either crash or give you wrong results.

**Comment by arachan** [comment]
Don't Japanese Columns deal?
No, some function to deal columns is work.

4 functions block Japanese character.

- ifxPy.fetch_both
- ifxPy.fetch_assoc
- IfxPy.field_name
- IfxPy.result

I read ifxpyc.c a little.
Maybe, PyObject* PyUnicode_AsASCIIString(PyObject *unicode) and StringOBJ_FromASCII is function to block non Ascii characters.

Is it no problem to remove PyUnicode_AsASCIIString and StringOBJ_FromASCII?
IfxPy.tables and IfxPy.columns can work fine without PyUnicode_AsASCIIString and StringOBJ_FromASCII.

## IfxPy.tables

work!
```python
# ommited ConnStr 
 conn=IfxPy.connect(ConnectionString,"","")
 
 try:
  conn = IfxPy.connect( ConStr, "", "")
 except Exception as e:
     print('ERROR:Connect failed')
     print(e)
     quit()
 
 
 # Table Name List
 if conn:
   result = IfxPy.tables(conn, None, 'schema','得意先m',"TABLE")
   i = 0
   row = IfxPy.fetch_both(result)
 
  while ( row ):
   print(row['TABLE_CAT'],row['TABLE_SCHEM'],row['TABLE_NAME'],row['TABLE_TYPE'],row['REMARKS'])
   i = i + 1
   row = IfxPy.fetch_both(result)
 
 IfxPy.close(conn)

```

**result**
```bash
 $ python3 ifxtablename.py 
 tablecat schema 得意先m TABLE None
```

## IfxPy.columns

work!
```python
 # ommited ConnStr 
 conn=IfxPy.connect(ConnectionString,"","")
 
 if conn:
     result=IfxPy.columns(conn,None,"schema","得意先m","得意先cd")
     i = 0
     row = IfxPy.fetch_both(result)
     while ( row ):
       print (row['TABLE_SCHEM'], row['TABLE_NAME'], row['COLUMN_NAME'], row['IS_NULLABLE'])
       i = i + 1
       row = IfxPy.fetch_both(result)
 else:
     print("no connection: "+IfxPy.conn_errormsg())
```

**result**
```bash
 $ python3 ifxcolumns1.py
 schema 得意先m 得意先cd NO
```

## IfxPy.field_name
don't work!

**code**
```python
 # ommited ConnStr
 conn=IfxPy.connect(ConnectionString,"","")
 
 try:
  	conn = IfxPy.connect( ConStr, "", "")
 except Exception as e:
     print('ERROR:Connect failed')
     print(e)
     quit()
 
 
 sql="SELECT 得意先名 from 得意先m where 得意先cd=1"
 stmt=IfxPy.exec_immediate(conn,sql)
 
 print(IfxPy.field_name(stmt,0))
 
 IfxPy.free_stmt(stmt)
 IfxPy.close(conn)
```


**result**
```bash
 $ python3 ifxfieldname.py 
 Traceback (most recent call last):
   File "ifxfieldname.py", line 19, in <module>
     print(IfxPy.field_name(stmt,0))
 UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
```

**Comment by jsagrera** [comment]
Yes, that's the problem, our code assumes the columns names can be converted to plain ASCII (1-byte characters) using calls like PyUnicode_AsASCIIString().  Multibyte strings (not just from Japanese codesets) may fail that process. 
We should convert strings coming from the driver to whatever codeset is defined in CLIENT_LOCALE, or at least use something more "generic" such as UTF8 (PyUnicode_DecodeUTF8()). 

It is one of the things in our 'TODO' list.

**Comment by arachan** [comment]
OK,
I'm looking forward to do your TODO list.
