### ISSUE TITLE
Error -23101 when trying to connect.

### ISSUE THREAD

**Issue by flakobatako** [OpenInformix/IfxPy#24]
I'm getting this error when thrying to connect.

ERROR: Connect failed
[Informix][Informix ODBC Driver][Informix]Unspecified System Error =  -23101. SQLCODE=-23101

Informix CSDK is installed at:
/opt/IBM/Informix_Client-SDK

My environment variables are like follows:
export LD_LIBRARY_PATH=/opt/IBM/Informix_Client-SDK/gls:/opt/IBM/Informix_Client-SDK/lib:/opt/IBM/Informix_Client-SDK/lib/esql:/opt/IBM/Informix_Client-SDK/lib/cli:/opt/oracle/instantclient_12_2:$LD_LIBRARY_PATH

I installed this CLISDK: ibm.csdk.4.50.FC2.LNX.tar.

My Python version is: 
Python 3.7.4 64 bit

Also tried with:
Python 3.6.7 64 bit

Here's my little script:

import IfxPy

ConStr = "SERVER=[theserver];DATABASE=[somedb];HOST=[serverip];SERVICE=[theport];UID=[theuser];PWD=[thepassword];"

try:
    conn = IfxPy.connect(ConStr, "clipcob", "t3st1ng")
except Exception as e:
    print ('ERROR: Connect failed')
    print (e)
    quit()

**Comment by jsagrera** [comment]
You are getting a "generic"  "Unspecified System Error" instead of the proper text which usually means that the message files failed to load. Make sure you have the INFORMIXDIR env variable set (that's what Informix uses to pick the messages), In your system it should be set to  '/opt/IBM/Informix_Client-SDK'

**Comment by flakobatako** [comment]
> You are getting a "generic" "Unspecified System Error" instead of the proper text which usually means that the message files failed to load. Make sure you have the INFORMIXDIR env variable set (that's what Informix uses to pick the messages), In your system it should be set to '/opt/IBM/Informix_Client-SDK'

Now my env variables look like this:
export INFORMIXDIR=/opt/IBM/Informix_Client-SDK
export LD_LIBRARY_PATH=${INFORMIXDIR}/lib:${INFORMIXDIR}/lib/esql:${INFORMIXDIR}/lib/cli:/opt/oracle/instantclient_12_2:$LD_LIBRARY_PATH

And when i echoed LD_LIBRARY_PATH it gives the correct paths:
echo $LD_LIBRARY_PATH
/opt/IBM/Informix_Client-SDK/lib:/opt/IBM/Informix_Client-SDK/lib/esql:/opt/IBM/Informix_Client-SDK/lib/cli:/opt/oracle/instantclient_12_2:

Now the error is like this:
ERROR: Connect failed
[Informix][Informix ODBC Driver][Informix]Sqlhosts file not found or cannot be opened. SQLCODE=-25553

I'm on Linux Mint 19.1 64 bit Cinnamon.

Edit: Nevermind. I had to set up my hosts file. Thank you very much.

**Comment by flakobatako** [comment]
Had to configure the sqlhosts file. Works like a charm both locally and in AWS Lambda.
