### ISSUE TITLE
ImportError: DLL load failed: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by Amrouane** [OpenInformix/IfxPy#31]
I get the error ImportError: `DLL load failed: %1 is not a valid Win32 application` when i try to import IfxPy:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-77ef8b2ad358> in <module>
----> 1 import IfxPy

ImportError: DLL load failed: %1 is not a valid Win32 application.
```

informix Clinet-SDK vesrion: **4.10.TC9**

PS: my server is running correctly, Ican connect to my database with RazorSQL fine with no problems

**Comment by rhtpandeyIN** [comment]
Hi @Amrouane , which version of Python you are using?

**Comment by Amrouane** [comment]
@rhtpandeyIN I am using `python 3.7`

**Comment by rhtpandeyIN** [comment]
I guess you are using python 32 bit version then, try with a 64 bit version of Python and let us know the output.

**Comment by Amrouane** [comment]
I'm pretty sure it's the x64 bit version of python i'm running. I tested with this code:
```
> import struct
> print( 8 * struct.calcsize("P"))
> 64
```
 another test with:
```
> import ctypes
> print (ctypes.sizeof(ctypes.c_voidp))
> 8 #4 for 32 bit and 8 for 64 bit.
```
So maybe the CSDK is 32 bit. I tried to download the x64 bit version but i can't download it with the link in the docs.
my current SDK version was downloaded from [here](https://www.ciscounitytools.com/Applications/CxN/InformixODBC/InformixODBC.html)

**Comment by jsagrera** [comment]
4.10.TC9 (anything with a 'T' in the suffix) is a 32-bit version. Your Python has to match the same architecture as the CSDK libraries.
You should be able to download a Developer edition (free) 64-bit CSDK from https://www-01.ibm.com/marketing/iwm/iwm/web/preLogin.do?source=ifxdl&S_PKG=410FC8dewin&lang=en_US  (you may need to create an IBM account). Something 4.10.FC12 or 4.50.FC2 should do fine. (The 'F' in the name indicates a 64-bit version)

**Comment by Amrouane** [comment]
@jsagrera Thanks,I changed CSDK to 4.50.FC2, added INFORMIXDIR to path and it worked like a charm.

**Comment by jgerhdz** [comment]
How did you overcame this message? I am having the same issue?
Note: In my case I have the clientsdk.4.10.TC9DE.WIN and the Python 32 and got the same error.

```
p\IfxPy> python -VV
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)]
```
`ImportError: DLL load failed while importing IfxPy: %1 is not a valid Win32 application`

I am trying to get 4.50.FC2 from IBM but I always get
`An error has occurred

This product is subject to strict US export control laws. Prior to providing access, we must validate whether you are eligible to receive it under an available US export authorization.Your request is being reviewed.Upon completion of this review, you will be contacted if we are able to give access.We apologize for any inconvenience.`

Could someone help me to get the 4.50.FC2?

Should I uninstall python 32 and and install 64?

**Comment by jsagrera** [comment]
The version of of CSDK depends on the version of Python.
CSDK 4.50 is only available on 64-bit, so if you want to use that CSDK version you need a 64-bit Python.

Python 3.8 has made a nasty change in how it resolves DLLs. Before 3.8 it was following what every other Windows application does tries to load DLLs from all the directories included in the %PATH% environment variable. Now you need to manually add which directories you want with add_dll_directory():

    import os
    if 'INFORMIXDIR' in os.environ:
        os.add_dll_directory(os.path.join(os.environ['INFORMIXDIR'],"bin"))
    import IfxPy
            
    ConStr="Driver={IBM INFORMIX ODBC DRIVER};SERVER=ids1210;DATABASE=stores7;"
    conn=IfxPy.connect(ConStr,"informix","pswd")
    
If you want to use 4.50, download the latest version (4.50.FC4W1), check that you can connect (e.g. create an ODBC DSN to your server) and then try from Python using the 'extra' lines I quoted above.

**Comment by zdenop** [comment]
`os.add_dll_directory` is present only in python 3.8 (windows?), so this is following code is more portable to import IfxPy: (personally I would prefer solution within module)

```
import os

if os.name == 'nt' and hasattr(os, 'add_dll_directory'):
    informixdir = os.getenv('INFORMIXDIR', None)
    if informixdir and os.path.exists(informixdir):
        os.add_dll_directory(os.path.join(informixdir, "bin"))

import IfxPy
        
ConStr="Driver={IBM INFORMIX ODBC DRIVER};SERVER=ids1210;DATABASE=stores7;"
conn=IfxPy.connect(ConStr,"informix","pswd")
```

See #41.

**Comment by FlyingJaco** [comment]
> `os.add_dll_directory` is present only in python 3.8 (windows?), so this is following code is more portable to import IfxPy: (personally I would prefer solution within module)
> 
> ```
> import os
> 
> if os.name == 'nt' and hasattr(os, 'add_dll_directory'):
>     informixdir = os.getenv('INFORMIXDIR', None)
>     if informixdir and os.path.exists(informixdir):
>         os.add_dll_directory(os.path.join(informixdir, "bin"))
> 
> import IfxPy
>         
> ConStr="Driver={IBM INFORMIX ODBC DRIVER};SERVER=ids1210;DATABASE=stores7;"
> conn=IfxPy.connect(ConStr,"informix","pswd")
> ```
> 
> See #41.

Can confirm that this works with Python 3.9 64-bit as well.
