### ISSUE TITLE
Django?

### ISSUE THREAD

**Issue by briandant** [OpenInformix/IfxPy#38]
I see that Django is on the roadmap. How far along are you with thinking about a Django integration? I could potentially help, depending of course on how much work this would be and the feasibility of the implementation.

**Comment by msatyan** [comment]
We welcome collaboration and any help is appreciated, please feel free to send us pull request.
Currently the relative priority is higher on SQLAlchemy over Django; we are somewhat half way Alchemy and it can be tracked.  
https://github.com/OpenInformix/InformixAlchemy

Regards

**Comment by briandant** [comment]
Glad to hear it. Many thanks for the quick update. I'll be in touch.
