### ISSUE TITLE
test_000_PrepareDb.IfxPyTestCase: Smart-large-object error. SQLCODE=-9810

### ISSUE THREAD

**Issue by arozehnal** [OpenInformix/IfxPy#49]
I  successfully build 64-bit version of IfxPy.so for AIX.
I'm  usinq python3 and CSDK_4.50.FC3
The first test test_001_ConnDb.py finished OK,

The second test crashed:

test_000_PrepareDb (test_000_PrepareDb.IfxPyTestCase) ... ERROR
 
=====================================================
ERROR: test_000_PrepareDb (test_000_PrepareDb.IfxPyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/itxwork/RO/t2/IfxPy/IfxPy/tests/test_000_PrepareDb.py", line 20, in test_000_PrepareDb
    obj.assert_expect(self.run_test_000)
  File "/itxwork/RO/t2/IfxPy/IfxPy/testfunctions.py", line 82, in assert_expect
    self.assertEqual(self.capture(testFuncName), self.expected_IDS(callstack[1][1]))
  File "/itxwork/RO/t2/IfxPy/IfxPy/testfunctions.py", line 50, in capture
    func()
  File "/itxwork/RO/t2/IfxPy/IfxPy/tests/test_000_PrepareDb.py", line 93, in run_test_000
    result = IfxPy.execute(stmt)
Exception: Statement Execute Failed: [Informix][Informix ODBC Driver][Informix]Smart-large-object error. SQLCODE=-9810

What's wrong with it? Any suggestion?

**Comment by deokershesh** [comment]
-9810 error code seems generic with respect to Smart Lob objects. Any other
error code(ISAM) that it provides?

If you have not created Smart Large Object Space (aka sbspace refer
Onconfig file of Informix server), then you must create the same using
"onspaces" utility on Informix sever side.

Thanks
-Shesh

**Comment by arozehnal** [comment]
Hi Shesh,
thank you for your advice, But I have Informix db engine instance with Smart BloB Space.
` 
IBM Informix Dynamic Server Version 14.10.FC3X1DE -- On-Line -- Up 00:53:49 -- 5377168 Kbytes
 
Dbspaces
address          number   flags      fchunk   nchunks  pgsize   flags    owner    name
700000020ee8028  1        0x4060001  1        1        4096     N  BA    informix rootdbs
700000021322da0  2        0x4040001  2        1        4096     N  BA    informix adisdbs
700000021306050  3        0x4040001  3        1        4096     N  BA    informix indxdbs
700000021306290  4        0x4040001  4        1        4096     N  BA    informix llogdbs
7000000213064d0  5        0x4042001  5        1        4096     N TBA    informix tmp1dbs
700000021306710  6        0x4068001  6        1        4096     N SBA    informix sbsdbs
 6 active, 2047 maximum
 
Chunks
address          chunk/dbs     offset     size       free       bpages     flags pathname
700000020ee8268  1      1      1          311295     281868                PO-B-- /informix/chunks/lrootdbs
7000000227f0028  2      2      1          524287     390989                PO-B-- /informix/chunks/ladisdbs
7000000227f1028  3      3      1          262143     256190                PO-B-- /informix/chunks/lindxdbs
7000000227f2028  4      4      1          131071     3018                  PO-B-- /informix/chunks/lllogdbs
7000000227f3028  5      5      1          131071     131018                PO-B-- /informix/chunks/ltmp1dbs
7000000227f4028  6      6      1          524287     489610     489610     POSB-- /informix/chunks/lrsbsdbs
                                 Metadata 34624      22400      34624
`
I have some experiences with Informix, but I'm newbie to Python.
When the test_000_PrepareDb.py crashed so it didn't occur to me to look into the db. 
Now, I see three tables was created (animals, animal_pics and anime_cat). 
I'm able to drop them. When I repeat the start ' python3 tests.py'
 the situation repeats, the tables are created, but the program crashes

`test_000_PrepareDb (test_000_PrepareDb.IfxPyTestCase) ... ERROR
 
======================================================================
ERROR: test_000_PrepareDb (test_000_PrepareDb.IfxPyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/itxwork/RO/t2/IfxPy/IfxPy/tests/test_000_PrepareDb.py", line 20, in test_000_PrepareDb
    obj.assert_expect(self.run_test_000)
  File "/itxwork/RO/t2/IfxPy/IfxPy/testfunctions.py", line 82, in assert_expect
    self.assertEqual(self.capture(testFuncName), self.expected_IDS(callstack[1][1]))
  File "/itxwork/RO/t2/IfxPy/IfxPy/testfunctions.py", line 50, in capture
    func()
  File "/itxwork/RO/t2/IfxPy/IfxPy/tests/test_000_PrepareDb.py", line 93, in run_test_000
    result = IfxPy.execute(stmt)
Exception: Statement Execute Failed: [Informix][Informix ODBC Driver][Informix]Smart-large-object error. SQLCODE=-
9810
 
----------------------------------------------------------------------
Ran 1 test in 0.038s
 
FAILED (errors=1)
`

**Comment by jsagrera** [comment]
Looking at your output, you do have a SmartBlob space (sbsdbs), What do you have defined in the onconfig as default SBS?

D:\Infx\ids1410\ssl\x>onstat -c | grep SBSPACENAME
# SBSPACENAME    - The default sbspace name where smart large objects
# SYSSBSPACENAME - The default sbspace for system statistics
SBSPACENAME     sbspace # Default sbspace
SYSSBSPACENAME  sbspace # Default System sbspace

D:\Infx\ids1410\ssl\x>

That's what the server will use to create any smart object (CLOB/BLOB).

If they are not set, change it and bounce the engine.

**Comment by arozehnal** [comment]
@jsagrera 
you're right... the settings of SBSPACENAME in onconfig had to be adjusted. 
test_000_PrepareDb.IfxPyTestCase finished now OK  :-)
Thank you.
