### ISSUE TITLE
ERROR: IfxPy-3.0.3-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by arozehnal** [OpenInformix/IfxPy#51]
I'm not able to install prebuild Windows driver due

pip3 install IfxPy-3.0.3-cp37-cp37m-win_amd64.whl
ERROR: IfxPy-3.0.3-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform

I have Win 10 64bits, Python 3.7.5

**Comment by jsagrera** [comment]
Quick test:

    d:\Infx\OpenInformix\IfxPy>pip3 install d:\infx\openinformix\ifxpy\ifxpy-3.0.3-cp37-cp37m-win_amd64.whl
    Processing d:\infx\openinformix\ifxpy\ifxpy-3.0.3-cp37-cp37m-win_amd64.whl
    Installing collected packages: ifxpy
    Successfully installed ifxpy-3.0.3

    d:\Infx\OpenInformix\IfxPy>python --version
    Python 3.7.4

    d:\Infx\OpenInformix\IfxPy>

Is your Python 64-bit or 32-bit? If is 32-bit the error would be expected:

    d:\Infx>python --
    Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [**MSC v.1900 32 bit (Intel)] on win32**
    Type "help", "copyright", "credits" or "license" for more information.
    >>> ^Z


    d:\Infx>pip3 install d:\infx\openinformix\ifxpy\ifxpy-3.0.3-cp37-cp37m-win_amd64.whl
    ifxpy-3.0.3-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.
    You are using pip version 18.0, however version 20.2.2 is available.
    You should consider upgrading via the 'python -m pip install --upgrade pip' command.

    d:\Infx>

**Comment by arozehnal** [comment]
I have a 32-bit version of Python installed.
I would like to keep it that way.
Prebuild IfxPy driver for Windows are only for the 64-bit version of Python?

**Comment by jsagrera** [comment]
There are only x64 prebuilt images. If you want 32-bit you will need to build it from source.

**Comment by arozehnal** [comment]
OK, thank you for your explanation.

**Comment by jsagrera** [comment]
If you go that route, remember to use the "disable_smart_triggers" flag during the build. 

    python setup.py build --disable_smart_triggers

32-bit CSDK ODBC doesn't have support for Smart Triggers.
