### ISSUE TITLE
ModuleNotFoundError: No module named 'IfxPyDbi'

### ISSUE THREAD

**Issue by garysan** [OpenInformix/IfxPy#53]
After upgrade IfxPy from 3.0.1 to 3.0.4 using pip, i have this error:

ModuleNotFoundError: No module named 'IfxPyDbi'

**on uninstall ifxpy v3.0.4:**
(microservicio) [gsandi@api microservicio]$ pip3 uninstall ifxpy
Found existing installation: IfxPy 3.0.4
Uninstalling IfxPy-3.0.4:
  Would remove:
    /home/gsandi/microservicio/lib/python3.6/site-packages/IfxPy-3.0.4.dist-info/*
    /home/gsandi/microservicio/lib/python3.6/site-packages/IfxPy.cpython-36m-x86_64-linux-gnu.so

**on v 3.0.1:**
(microservicio) [gsandi@api microservicio]$ pip3 uninstall ifxpy
Found existing installation: IfxPy 3.0.1
Uninstalling IfxPy-3.0.1:
  Would remove:
    /home/gsandi/microservicio/lib/python3.6/site-packages/IfxPy-3.0.1.dist-info/*
    /home/gsandi/microservicio/lib/python3.6/site-packages/IfxPy.cpython-36m-x86_64-linux-gnu.so
    **/home/gsandi/microservicio/lib/python3.6/site-packages/IfxPyDbi.py**

Why the file ifxpydbi.py is not copied during installation of  the new version of IfxPy?

Rgrds.

**Comment by deokershesh** [comment]
Hi Gary,

For some reason IfxPyDbi.py got missed into 3.0.4 version. We have created
a new version 3.0.5 and it should work as expected. Kindly give it a try.

Thanks & Regards
-Shesh

**Comment by garysan** [comment]
Thanks!
