### ISSUE TITLE
No output for python 3.12.8 (Windows)

### ISSUE THREAD

**Issue by zdenop** [OpenInformix/IfxPy#83]
I have simple test script:
```py
import os
os.add_dll_directory(r"c:\Program Files\IBM Informix Client SDK\bin")

import IfxPy
print("After import")

con_str = "Host=..."
conn = IfxPy.connect(con_str, '', '')
print("After conn")

sql =  "SELECT DBINFO('version', 'full') FROM systables WHERE tabid = 1;"
stmt = IfxPy.exec_immediate(conn, sql)
print("After stmt")
dictionary = IfxPy.fetch_both(stmt)

print(dictionary)
IfxPy.close(conn)

```

On my old computer with python 3.11 (Windows 10 64bit) it produces:
```
After import
After conn
After stmt
{"import sys, types, os;has_mfs = sys.version_info > (3, 5);p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('google',));importlib = has_mfs and __import__('importlib.util');has_mfs and __import__('importlib.machinery');m = has_mfs and sys.modules.setdefault('google', importlib.util.module_from_spec(importlib.machinery.PathFinder.find_spec('google', [os.path.dirname(p)])));m = m or sys.modules.setdefault('google', types.ModuleType('google'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p)\n": 'IBM Informix Dynamic Server Version 12.10.FC7WE', 0: 'IBM Informix Dynamic Server Version 12.10.FC7WE'}
```

On my new computer with python 3.12 (Windows 11 64bit) it produces just.:
```
After import

```

e.g. it crash during connect  without any information. Any idea what could be problem or how to debug/solve it?

**Comment by jsagrera** [comment]
Stack trace will help but for that you will need a debugger (windbg)
Did you use the same binaries (Ifxpy/CSDK) you had in W10? 
Could be due some change between 3.12 and 3.11 but doesn't sound likely. 
Does basic connectivity (like ODBC) work on the W11?

**Comment by zdenop** [comment]
windbg is installed on computer.
There is the same installation of IBM client (IBM Informix Client SDK 4.10.FC4)
I can connect to informix db (from new computer) with dbaccess.exe (part of IBM client).

Tried to run python 3.12 on old computer and I got the same results as on new:
```sh
pip install -U uv
uv venv --python 3.12
.venv\Scripts\activate

SET "INFORMIXDIR=C:\Program Files\IBM Informix Client SDK"
SET PATH=%INFORMIXDIR%\bin;%PATH%
SET CSDK_HOME=%INFORMIXDIR%

uv pip install f:\Projects\Work\IfxPy\IfxPy\dist\IfxPy-3.0.5-cp312-cp312-win_amd64.whl
test_ifx.py
After import
```

When I do the same but with `uv venv --python 3.11` - it works (on old and new computer)
 So I guess there is problem with python 3.12.

**Comment by jsagrera** [comment]
So it sounds 3.12 is incompatible with the current code.
I may try to built it but need to find a suitable box.

**Comment by jsagrera** [comment]
Something wrong in how we handle the connection string Unicode conversion. 

![image](https://github.com/user-attachments/assets/c7a63f85-94e5-40ee-b4de-1f59a66f07eb)

will check what's wrong asap.

**Comment by zdenop** [comment]
Thanks! Now it works!
